use std::path::PathBuf;

const SOURCE: &str = "data/Adobe-Japan1-UCS2";
const TARGET: &str = "japan1_table.rs";
const SECTIONS: [(&str, &str, usize); 2] = [
    ("beginbfchar", "endbfchar", 2),
    ("beginbfrange", "endbfrange", 3),
];
const HEX_DIGITS: usize = 4;
const HEX_RADIX: u32 = 16;
const VARIATION_SELECTORS: [(u32, u32); 2] = [(0xFE00, 0xFE0F), (0xE0100, 0xE01EF)];
const REPLACEMENT: char = '\u{FFFD}';
const BMP_MAX: u32 = 0xFFFF;
const UNMAPPED: u16 = 0;
const CHARS_PER_ROW: usize = 12;
const HEADER: &str = "// Generated by build.rs from data/Adobe-Japan1-UCS2. Do not edit.\n\
                      // See NOTICE for the terms the mapping resource is distributed under.\n";

fn main() {
    println!("cargo::rerun-if-changed={SOURCE}");

    let source = std::fs::read_to_string(SOURCE)
        .unwrap_or_else(|error| panic!("cannot read {SOURCE}: {error}"));
    let target = PathBuf::from(std::env::var_os("OUT_DIR").expect("OUT_DIR is set")).join(TARGET);

    let code = |token: &[u16]| {
        token
            .iter()
            .fold(0u32, |code, unit| (code << 16) | u32::from(*unit))
    };
    let text = source.as_str();
    let blocks: Vec<(&str, usize)> = SECTIONS
        .iter()
        .flat_map(|&(begin, end, arity)| {
            text.match_indices(begin).map(move |(start, _)| {
                let body = &text[start + begin.len()..];
                (&body[..body.find(end).unwrap_or(body.len())], arity)
            })
        })
        .collect();

    let ranges: Vec<(u32, u32, Vec<u16>)> = blocks
        .iter()
        .flat_map(|&(block, arity)| {
            let tokens: Vec<Vec<u16>> = block
                .split('<')
                .skip(1)
                .filter_map(|token| token.split('>').next())
                .map(|token| {
                    token
                        .as_bytes()
                        .chunks(HEX_DIGITS)
                        .filter_map(|digits| {
                            u16::from_str_radix(std::str::from_utf8(digits).ok()?, HEX_RADIX).ok()
                        })
                        .collect()
                })
                .collect();

            tokens
                .chunks_exact(arity)
                .map(|entry| {
                    (
                        code(&entry[0]),
                        code(&entry[arity - 2]),
                        entry[arity - 1].clone(),
                    )
                })
                .collect::<Vec<_>>()
        })
        .collect();

    let mappings: Vec<(usize, String)> = ranges
        .iter()
        .flat_map(|(low, high, target)| {
            (0..=high.saturating_sub(*low)).filter_map(move |offset| {
                let units =
                    target
                        .iter()
                        .enumerate()
                        .map(|(at, unit)| match at + 1 == target.len() {
                            true => unit.wrapping_add(offset as u16),
                            false => *unit,
                        });
                let glyph: String = char::decode_utf16(units)
                    .filter_map(Result::ok)
                    .filter(|character| {
                        !VARIATION_SELECTORS
                            .iter()
                            .any(|(low, high)| (*low..=*high).contains(&u32::from(*character)))
                    })
                    .collect();

                (!glyph.is_empty() && !glyph.starts_with(REPLACEMENT))
                    .then_some(((low + offset) as usize, glyph))
            })
        })
        .collect();

    let count = mappings.iter().map(|(cid, _)| cid + 1).max().unwrap_or(0);
    let glyphs = mappings.iter().fold(
        vec![None; count],
        |mut glyphs: Vec<Option<&str>>, (cid, glyph)| {
            glyphs[*cid] = Some(glyph);
            glyphs
        },
    );

    let single = |glyph: &str| {
        let mut characters = glyph.chars();
        match (characters.next(), characters.next()) {
            (Some(character), None) if u32::from(character) <= BMP_MAX => {
                Some(u32::from(character) as u16)
            }
            _ => None,
        }
    };
    let chars: Vec<u16> = glyphs
        .iter()
        .map(|glyph| glyph.and_then(single).unwrap_or(UNMAPPED))
        .collect();
    let sequences: Vec<(usize, &str)> = glyphs
        .iter()
        .enumerate()
        .filter_map(|(cid, glyph)| {
            let glyph = (*glyph)?;
            single(glyph).is_none().then_some((cid, glyph))
        })
        .collect();

    let rows: String = chars
        .chunks(CHARS_PER_ROW)
        .map(|row| {
            let row: Vec<String> = row.iter().map(|char| format!("0x{char:04X}")).collect();
            format!("    {},\n", row.join(", "))
        })
        .collect();
    let entries: String = sequences
        .iter()
        .map(|(cid, glyph)| {
            let escaped: String = glyph
                .chars()
                .map(|character| match character {
                    '"' | '\\' => format!("\\{character}"),
                    control if control.is_control() => format!("\\u{{{:X}}}", u32::from(control)),
                    character => character.to_string(),
                })
                .collect();
            format!("    ({cid}, \"{escaped}\"),\n")
        })
        .collect();
    let rust = format!(
        "{HEADER}\n#[rustfmt::skip]\nstatic CHARS: [u16; {}] = [\n{rows}];\n\n\
         static SEQUENCES: [(u16, &str); {}] = [\n{entries}];\n",
        chars.len(),
        sequences.len()
    );

    std::fs::write(&target, rust)
        .unwrap_or_else(|error| panic!("cannot write {}: {error}", target.display()));
}
