name: On Pull Request(Python)
on:
  pull_request:
    branches:
      - master
    paths:
      - 'features/**'
      - 'tests/acceptance/**'
      - '.github/workflows/on-pullrequest-python.yml'

jobs:
  fetch-data:
    uses: ./.github/workflows/job-fetch-data.yml
  large-test:
    needs: fetch-data
    strategy:
      matrix:
        frontend: [wasm, cli]
    uses: ./.github/workflows/job-test-large.yml
    with:
      frontend: ${{ matrix.frontend }}
